"""Updated models testing

Revision ID: 0b9c6c8fef53
Revises: 6c6d998472b1
Create Date: 2022-08-04 14:19:09.875455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b9c6c8fef53'
down_revision = '6c6d998472b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_column('users', 'confirm_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirm_password', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###
