"""Updated user model

Revision ID: 6c6d998472b1
Revises: c45824a7e2f8
Create Date: 2022-08-04 13:08:54.559439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c6d998472b1'
down_revision = 'c45824a7e2f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirm_password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirm_password')
    # ### end Alembic commands ###
